spring:
  application:
    name: kodo-worker

  datasource:
    url: jdbc:postgresql://localhost:5434/kodo
    username: kodo
    password: kodo

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: telemetry-storage
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        "[spring.json.value.default.type]": "com.kodo.contracts.events.GameEvent"
        "[spring.json.trusted.packages]": "com.kodo.contracts.events"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

kodo:
  kafka:
    topic: telemetry.events
    dlt-topic: telemetry.events-dlt