spring:
  application:
    name: kodo-api

  datasource:
    url: jdbc:postgresql://localhost:5434/kodo
    username: kodo
    password: kodo

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092